services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - MERCADOPAGO_ACCESS_TOKEN=changeme
      - BASE_URL=${BASE_URL}
    ports:
      - "9080:3000"

  web-customer:
    build:
      context: .
      dockerfile: app-customer/Dockerfile
    depends_on:
      - app
    restart: unless-stopped
    ports:
      - "9081:80"

  web-staff:
    build:
      context: .
      dockerfile: app-staff/Dockerfile
    depends_on:
      - app
    restart: unless-stopped
    ports:
      - "9082:80"

volumes:
  redis-data:
    driver: local
